### ISSUE TITLE
Add Greek translation

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-bom#35]

**Comment by konyashkina** [comment]
Greek translation added to Jmix and works fine with dependency
`	implementation 'io.jmix.translations:jmix-translations-el'`
except cases described below.

Non-critical bug, but a notice: Greek text does not fit in some buttons and dialog windows. 	

**Case 0.** Quartz add-on is not translated. 

**Case 1.** Additional actions for User 

Add dependency
`	implementation 'io.jmix.translations:jmix-translations-el'`
and load  gradle changes. 

Run Jmix application. 
Open http://localhost:8080 in browser, select Greek language, login as default user.
Open main menu: Application > User 

Select an existing user record (or create a new one), click 'additional' button. 
	1. select Αλλαγή κωδικού πρόσβασης (Change password) from the drop-down list
	2. select Επαναφορά κωδικού πρόσβασης (Reset password) 
	3. select Επαναφορά διακριτικών της... (Reset 'remember me' tokens) 
	
**AR:** 
0. Text on the 'additional' button is not translated.  
1. Greek title does not fit in the dialog window. 
2. Greek title does not fit in the dialog window. 
3. 'Ακύρωση' button does not fit in the dialog window. 
    Greek title does not fit in the dialog window. 

![user-additional-text001](https://user-images.githubusercontent.com/85500330/158790672-c0760933-6958-42e3-b844-5a99d11a98f9.png)

![user-additional-text002](https://user-images.githubusercontent.com/85500330/158790684-ae9d6c1e-1533-495b-80ef-52c80a8c0d67.png)

![user-additional-text003](https://user-images.githubusercontent.com/85500330/158790698-8562cc09-9f80-4430-8d52-adc660f4cd84.png)


**Case 2.** Filter buttons

Add Reports add-on.
Run Jmix application. Open http://localhost:8080 in browser, select Greek language, login as default user.
Open main menu: Αναφορές > Εκτέλεση αναφορών
	(Reports > Run reports)
Take a look on the fiters buttons on the top. 
 
**AR:** Text on 'Search' (Αναζήτηση) and 'Clear' (Καθαρός) filter buttons does not fit in the buttons. 

![search-clear-buttons](https://user-images.githubusercontent.com/85500330/158790534-53d01a0b-b194-4ea9-92ec-f8786b7c5eb9.png)


**Case 3.**  Business calendar

_Case 3.1_
Add Business calendar add-on.
Run Jmix application. Open http://localhost:8080 in browser, select Greek language, login as default user.
Open main menu: Επαγγελματικα ημερολόγια
Add a new Business calendar or open an exising one. Go to 'Αργίες' (Holidays) tab. 
Click 'Δημιουργία' (Create) button. 
Select 'Ετήσια αργία' (Annual holiday) and then click 'Μηνας' (month) to open the list. 

**AR:** Month names are not translated.  

_Case 3.2_
Select 'Ημέρα της εβδομάδας' (Day of week), then click 'Κλείσιμο' (Cancel) button. 

**AR:** Days list is not translated. 
    Cancel button (on the right) does not fit in the dialog window. 

![businesscalendar](https://user-images.githubusercontent.com/85500330/158790739-b85e6f49-4270-4c9a-beb3-6017bf900595.png)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4124-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)

**Comment by konyashkina** [comment]
New ticket https://github.com/Haulmont/jmix-translations/issues/53 opened to fix cases described above.
